# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.WidgetManager = QtWidgets.QStackedWidget(self.centralwidget)
        self.WidgetManager.setGeometry(QtCore.QRect(10, 0, 951, 681))
        self.WidgetManager.setObjectName("WidgetManager")
        self.Menu = QtWidgets.QWidget()
        self.Menu.setObjectName("Menu")
        self.newGame_Button = QtWidgets.QPushButton(self.Menu)
        self.newGame_Button.setGeometry(QtCore.QRect(390, 210, 181, 61))
        self.newGame_Button.setObjectName("newGame_Button")
        self.loadGame_Button = QtWidgets.QPushButton(self.Menu)
        self.loadGame_Button.setGeometry(QtCore.QRect(390, 280, 181, 61))
        self.loadGame_Button.setObjectName("loadGame_Button")
        self.options_Button = QtWidgets.QPushButton(self.Menu)
        self.options_Button.setGeometry(QtCore.QRect(390, 350, 181, 61))
        self.options_Button.setObjectName("options_Button")
        self.WidgetManager.addWidget(self.Menu)
        self.NewGame = QtWidgets.QWidget()
        self.NewGame.setObjectName("NewGame")
        self.galacticArmy_Button = QtWidgets.QPushButton(self.NewGame)
        self.galacticArmy_Button.setGeometry(QtCore.QRect(170, 240, 211, 181))
        self.galacticArmy_Button.setObjectName("galacticArmy_Button")
        self.rebellion_Button = QtWidgets.QPushButton(self.NewGame)
        self.rebellion_Button.setGeometry(QtCore.QRect(460, 240, 211, 181))
        self.rebellion_Button.setObjectName("rebellion_Button")
        self.label = QtWidgets.QLabel(self.NewGame)
        self.label.setGeometry(QtCore.QRect(350, 130, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.WidgetManager.addWidget(self.NewGame)
        self.Map = QtWidgets.QWidget()
        self.Map.setObjectName("Map")
        self.mygeeto_Button = QtWidgets.QPushButton(self.Map)
        self.mygeeto_Button.setGeometry(QtCore.QRect(420, 170, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.mygeeto_Button.setPalette(palette)
        self.mygeeto_Button.setText("")
        self.mygeeto_Button.setObjectName("mygeeto_Button")
        self.Faction_Label = QtWidgets.QLabel(self.Map)
        self.Faction_Label.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.Faction_Label.setObjectName("Faction_Label")
        self.groupBox = QtWidgets.QGroupBox(self.Map)
        self.groupBox.setGeometry(QtCore.QRect(10, 480, 931, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.economy_Button = QtWidgets.QPushButton(self.groupBox)
        self.economy_Button.setGeometry(QtCore.QRect(140, 30, 121, 51))
        self.economy_Button.setObjectName("economy_Button")
        self.research_Button = QtWidgets.QPushButton(self.groupBox)
        self.research_Button.setGeometry(QtCore.QRect(270, 30, 121, 51))
        self.research_Button.setObjectName("research_Button")
        self.engineering_Button = QtWidgets.QPushButton(self.groupBox)
        self.engineering_Button.setGeometry(QtCore.QRect(400, 30, 121, 51))
        self.engineering_Button.setObjectName("engineering_Button")
        self.endTurn_Button = QtWidgets.QPushButton(self.groupBox)
        self.endTurn_Button.setGeometry(QtCore.QRect(10, 90, 121, 51))
        self.endTurn_Button.setObjectName("endTurn_Button")
        self.army_Button = QtWidgets.QPushButton(self.groupBox)
        self.army_Button.setGeometry(QtCore.QRect(10, 30, 121, 51))
        self.army_Button.setObjectName("army_Button")
        self.lineEdit = QtWidgets.QLineEdit(self.Map)
        self.lineEdit.setGeometry(QtCore.QRect(10, 650, 931, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.kamino_Button = QtWidgets.QPushButton(self.Map)
        self.kamino_Button.setGeometry(QtCore.QRect(170, 350, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.kamino_Button.setPalette(palette)
        self.kamino_Button.setText("")
        self.kamino_Button.setObjectName("kamino_Button")
        self.mustafar_Button = QtWidgets.QPushButton(self.Map)
        self.mustafar_Button.setGeometry(QtCore.QRect(800, 380, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.mustafar_Button.setPalette(palette)
        self.mustafar_Button.setText("")
        self.mustafar_Button.setObjectName("mustafar_Button")
        self.geonosis_Button = QtWidgets.QPushButton(self.Map)
        self.geonosis_Button.setGeometry(QtCore.QRect(800, 140, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.geonosis_Button.setPalette(palette)
        self.geonosis_Button.setText("")
        self.geonosis_Button.setObjectName("geonosis_Button")
        self.rhenVar_Button = QtWidgets.QPushButton(self.Map)
        self.rhenVar_Button.setGeometry(QtCore.QRect(60, 80, 41, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.rhenVar_Button.setPalette(palette)
        self.rhenVar_Button.setText("")
        self.rhenVar_Button.setObjectName("rhenVar_Button")
        self.label_3 = QtWidgets.QLabel(self.Map)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 61, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Map)
        self.label_4.setGeometry(QtCore.QRect(160, 330, 61, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Map)
        self.label_5.setGeometry(QtCore.QRect(410, 150, 61, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Map)
        self.label_6.setGeometry(QtCore.QRect(790, 120, 61, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Map)
        self.label_7.setGeometry(QtCore.QRect(790, 360, 61, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Credits_label = QtWidgets.QLabel(self.Map)
        self.Credits_label.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.Credits_label.setObjectName("Credits_label")
        self.rhenVarFaction_Label = QtWidgets.QLabel(self.Map)
        self.rhenVarFaction_Label.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.rhenVarFaction_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.rhenVarFaction_Label.setObjectName("rhenVarFaction_Label")
        self.kaminoFaction_Label = QtWidgets.QLabel(self.Map)
        self.kaminoFaction_Label.setGeometry(QtCore.QRect(140, 390, 101, 16))
        self.kaminoFaction_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.kaminoFaction_Label.setObjectName("kaminoFaction_Label")
        self.mygeetoFaction_Label = QtWidgets.QLabel(self.Map)
        self.mygeetoFaction_Label.setGeometry(QtCore.QRect(390, 210, 101, 16))
        self.mygeetoFaction_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.mygeetoFaction_Label.setObjectName("mygeetoFaction_Label")
        self.mustafarFactio_Label = QtWidgets.QLabel(self.Map)
        self.mustafarFactio_Label.setGeometry(QtCore.QRect(770, 420, 101, 16))
        self.mustafarFactio_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.mustafarFactio_Label.setObjectName("mustafarFactio_Label")
        self.geonosisFaction_Label = QtWidgets.QLabel(self.Map)
        self.geonosisFaction_Label.setGeometry(QtCore.QRect(770, 180, 101, 16))
        self.geonosisFaction_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.geonosisFaction_Label.setObjectName("geonosisFaction_Label")
        self.creditCount_Label = QtWidgets.QLabel(self.Map)
        self.creditCount_Label.setGeometry(QtCore.QRect(60, 30, 151, 16))
        self.creditCount_Label.setObjectName("creditCount_Label")
        self.planetSelected_Label = QtWidgets.QLabel(self.Map)
        self.planetSelected_Label.setGeometry(QtCore.QRect(20, 460, 241, 16))
        self.planetSelected_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.planetSelected_Label.setObjectName("planetSelected_Label")
        self.WidgetManager.addWidget(self.Map)
        self.Movement = QtWidgets.QWidget()
        self.Movement.setObjectName("Movement")
        self.fromPlanet_Label = QtWidgets.QLabel(self.Movement)
        self.fromPlanet_Label.setGeometry(QtCore.QRect(160, 160, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fromPlanet_Label.setFont(font)
        self.fromPlanet_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.fromPlanet_Label.setObjectName("fromPlanet_Label")
        self.toPlanet_Label = QtWidgets.QLabel(self.Movement)
        self.toPlanet_Label.setGeometry(QtCore.QRect(510, 160, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.toPlanet_Label.setFont(font)
        self.toPlanet_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.toPlanet_Label.setObjectName("toPlanet_Label")
        self.Label_18 = QtWidgets.QLabel(self.Movement)
        self.Label_18.setGeometry(QtCore.QRect(230, 220, 81, 16))
        self.Label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_18.setObjectName("Label_18")
        self.Label_17 = QtWidgets.QLabel(self.Movement)
        self.Label_17.setGeometry(QtCore.QRect(590, 220, 81, 16))
        self.Label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_17.setObjectName("Label_17")
        self.fromFaction_Label = QtWidgets.QLabel(self.Movement)
        self.fromFaction_Label.setGeometry(QtCore.QRect(160, 150, 221, 16))
        self.fromFaction_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.fromFaction_Label.setObjectName("fromFaction_Label")
        self.toFaction_Label = QtWidgets.QLabel(self.Movement)
        self.toFaction_Label.setGeometry(QtCore.QRect(550, 150, 181, 16))
        self.toFaction_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.toFaction_Label.setObjectName("toFaction_Label")
        self.fromTo_Send = QtWidgets.QPushButton(self.Movement)
        self.fromTo_Send.setGeometry(QtCore.QRect(390, 370, 131, 81))
        self.fromTo_Send.setObjectName("fromTo_Send")
        self.fromTo_Cancel = QtWidgets.QPushButton(self.Movement)
        self.fromTo_Cancel.setGeometry(QtCore.QRect(390, 470, 131, 81))
        self.fromTo_Cancel.setObjectName("fromTo_Cancel")
        self.label_19 = QtWidgets.QLabel(self.Movement)
        self.label_19.setGeometry(QtCore.QRect(400, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.fromToInput_LineEdit = QtWidgets.QLineEdit(self.Movement)
        self.fromToInput_LineEdit.setGeometry(QtCore.QRect(400, 280, 113, 22))
        self.fromToInput_LineEdit.setObjectName("fromToInput_LineEdit")
        self.label_20 = QtWidgets.QLabel(self.Movement)
        self.label_20.setGeometry(QtCore.QRect(380, 300, 161, 16))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.movementStatus_Label = QtWidgets.QLabel(self.Movement)
        self.movementStatus_Label.setGeometry(QtCore.QRect(430, 110, 55, 16))
        self.movementStatus_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.movementStatus_Label.setObjectName("movementStatus_Label")
        self.label_38 = QtWidgets.QLabel(self.Movement)
        self.label_38.setGeometry(QtCore.QRect(160, 240, 221, 16))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.Movement)
        self.label_40.setGeometry(QtCore.QRect(600, 240, 81, 16))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.fromTroops_Label = QtWidgets.QLabel(self.Movement)
        self.fromTroops_Label.setGeometry(QtCore.QRect(310, 220, 81, 16))
        self.fromTroops_Label.setObjectName("fromTroops_Label")
        self.toTroops_Label = QtWidgets.QLabel(self.Movement)
        self.toTroops_Label.setGeometry(QtCore.QRect(680, 220, 91, 16))
        self.toTroops_Label.setObjectName("toTroops_Label")
        self.WidgetManager.addWidget(self.Movement)
        self.Army = QtWidgets.QWidget()
        self.Army.setObjectName("Army")
        self.armyCalculate_Button = QtWidgets.QPushButton(self.Army)
        self.armyCalculate_Button.setGeometry(QtCore.QRect(410, 420, 121, 41))
        self.armyCalculate_Button.setObjectName("armyCalculate_Button")
        self.armyPlanetSelection_Combo = QtWidgets.QComboBox(self.Army)
        self.armyPlanetSelection_Combo.setGeometry(QtCore.QRect(410, 370, 121, 41))
        self.armyPlanetSelection_Combo.setObjectName("armyPlanetSelection_Combo")
        self.armyInput_Entry = QtWidgets.QLineEdit(self.Army)
        self.armyInput_Entry.setGeometry(QtCore.QRect(410, 330, 121, 31))
        self.armyInput_Entry.setObjectName("armyInput_Entry")
        self.label_28 = QtWidgets.QLabel(self.Army)
        self.label_28.setGeometry(QtCore.QRect(300, 110, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.armyCost_Label = QtWidgets.QLabel(self.Army)
        self.armyCost_Label.setGeometry(QtCore.QRect(540, 340, 121, 16))
        self.armyCost_Label.setObjectName("armyCost_Label")
        self.armyUpkeep_Label = QtWidgets.QLabel(self.Army)
        self.armyUpkeep_Label.setGeometry(QtCore.QRect(540, 360, 111, 16))
        self.armyUpkeep_Label.setObjectName("armyUpkeep_Label")
        self.armyCredits_Label = QtWidgets.QLabel(self.Army)
        self.armyCredits_Label.setGeometry(QtCore.QRect(540, 320, 111, 16))
        self.armyCredits_Label.setObjectName("armyCredits_Label")
        self.armyCancel_Button = QtWidgets.QPushButton(self.Army)
        self.armyCancel_Button.setGeometry(QtCore.QRect(410, 570, 121, 41))
        self.armyCancel_Button.setObjectName("armyCancel_Button")
        self.armyOrder_Button = QtWidgets.QPushButton(self.Army)
        self.armyOrder_Button.setEnabled(False)
        self.armyOrder_Button.setGeometry(QtCore.QRect(410, 470, 121, 41))
        self.armyOrder_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.armyOrder_Button.setObjectName("armyOrder_Button")
        self.WidgetManager.addWidget(self.Army)
        self.Economy = QtWidgets.QWidget()
        self.Economy.setObjectName("Economy")
        self.label_26 = QtWidgets.QLabel(self.Economy)
        self.label_26.setGeometry(QtCore.QRect(290, 50, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.frame = QtWidgets.QFrame(self.Economy)
        self.frame.setGeometry(QtCore.QRect(290, 120, 161, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.economyCreditsTurn_Label = QtWidgets.QLabel(self.frame)
        self.economyCreditsTurn_Label.setGeometry(QtCore.QRect(80, 40, 71, 16))
        self.economyCreditsTurn_Label.setObjectName("economyCreditsTurn_Label")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(0, 20, 51, 16))
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.economyCredits_Label = QtWidgets.QLabel(self.frame)
        self.economyCredits_Label.setGeometry(QtCore.QRect(50, 20, 81, 16))
        self.economyCredits_Label.setObjectName("economyCredits_Label")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(0, 40, 81, 16))
        self.label_23.setObjectName("label_23")
        self.frame_2 = QtWidgets.QFrame(self.Economy)
        self.frame_2.setGeometry(QtCore.QRect(470, 120, 161, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.economyBonds_Label = QtWidgets.QLabel(self.frame_2)
        self.economyBonds_Label.setGeometry(QtCore.QRect(80, 60, 71, 16))
        self.economyBonds_Label.setObjectName("economyBonds_Label")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(0, 40, 51, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.economyTaxes_Label = QtWidgets.QLabel(self.frame_2)
        self.economyTaxes_Label.setGeometry(QtCore.QRect(50, 40, 81, 16))
        self.economyTaxes_Label.setObjectName("economyTaxes_Label")
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(0, 60, 81, 16))
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        self.label_39.setGeometry(QtCore.QRect(0, 20, 51, 16))
        self.label_39.setObjectName("label_39")
        self.economyIncome_Label = QtWidgets.QLabel(self.frame_2)
        self.economyIncome_Label.setGeometry(QtCore.QRect(50, 20, 81, 16))
        self.economyIncome_Label.setObjectName("economyIncome_Label")
        self.frame_3 = QtWidgets.QFrame(self.Economy)
        self.frame_3.setGeometry(QtCore.QRect(470, 220, 161, 101))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_41 = QtWidgets.QLabel(self.frame_3)
        self.label_41.setGeometry(QtCore.QRect(0, 20, 91, 16))
        self.label_41.setObjectName("label_41")
        self.economyUpkeep_Label = QtWidgets.QLabel(self.frame_3)
        self.economyUpkeep_Label.setGeometry(QtCore.QRect(90, 20, 81, 16))
        self.economyUpkeep_Label.setObjectName("economyUpkeep_Label")
        self.label_45 = QtWidgets.QLabel(self.frame_3)
        self.label_45.setGeometry(QtCore.QRect(0, 0, 61, 16))
        self.label_45.setObjectName("label_45")
        self.economyCancel_Button = QtWidgets.QPushButton(self.Economy)
        self.economyCancel_Button.setGeometry(QtCore.QRect(410, 580, 111, 41))
        self.economyCancel_Button.setObjectName("economyCancel_Button")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Economy)
        self.groupBox_6.setGeometry(QtCore.QRect(350, 330, 231, 211))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.economyTaxesOutput_Label = QtWidgets.QLabel(self.groupBox_6)
        self.economyTaxesOutput_Label.setGeometry(QtCore.QRect(60, 30, 111, 16))
        self.economyTaxesOutput_Label.setText("")
        self.economyTaxesOutput_Label.setObjectName("economyTaxesOutput_Label")
        self.economy9_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy9_Button.setGeometry(QtCore.QRect(140, 120, 31, 28))
        self.economy9_Button.setObjectName("economy9_Button")
        self.economyE_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economyE_Button.setGeometry(QtCore.QRect(140, 150, 31, 28))
        self.economyE_Button.setObjectName("economyE_Button")
        self.economy1_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy1_Button.setGeometry(QtCore.QRect(60, 60, 31, 28))
        self.economy1_Button.setObjectName("economy1_Button")
        self.economyC_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economyC_Button.setGeometry(QtCore.QRect(60, 150, 31, 28))
        self.economyC_Button.setObjectName("economyC_Button")
        self.economy3_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy3_Button.setGeometry(QtCore.QRect(140, 60, 31, 28))
        self.economy3_Button.setObjectName("economy3_Button")
        self.economy6_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy6_Button.setGeometry(QtCore.QRect(140, 90, 31, 28))
        self.economy6_Button.setObjectName("economy6_Button")
        self.economy8_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy8_Button.setGeometry(QtCore.QRect(100, 120, 31, 28))
        self.economy8_Button.setObjectName("economy8_Button")
        self.economy7_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy7_Button.setGeometry(QtCore.QRect(60, 120, 31, 28))
        self.economy7_Button.setObjectName("economy7_Button")
        self.economy4_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy4_Button.setGeometry(QtCore.QRect(60, 90, 31, 28))
        self.economy4_Button.setObjectName("economy4_Button")
        self.economy0_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy0_Button.setGeometry(QtCore.QRect(100, 150, 31, 28))
        self.economy0_Button.setObjectName("economy0_Button")
        self.economy5_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy5_Button.setGeometry(QtCore.QRect(100, 90, 31, 28))
        self.economy5_Button.setObjectName("economy5_Button")
        self.economy2_Button = QtWidgets.QPushButton(self.groupBox_6)
        self.economy2_Button.setGeometry(QtCore.QRect(100, 60, 31, 28))
        self.economy2_Button.setObjectName("economy2_Button")
        self.WidgetManager.addWidget(self.Economy)
        self.Research = QtWidgets.QWidget()
        self.Research.setObjectName("Research")
        self.pushButton_13 = QtWidgets.QPushButton(self.Research)
        self.pushButton_13.setGeometry(QtCore.QRect(430, 630, 93, 28))
        self.pushButton_13.setObjectName("pushButton_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Research)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 60, 201, 551))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Research)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 60, 231, 551))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Research)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 60, 231, 551))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Research)
        self.groupBox_5.setGeometry(QtCore.QRect(720, 60, 211, 551))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_9 = QtWidgets.QLabel(self.Research)
        self.label_9.setGeometry(QtCore.QRect(410, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.WidgetManager.addWidget(self.Research)
        self.Engineering = QtWidgets.QWidget()
        self.Engineering.setObjectName("Engineering")
        self.label_10 = QtWidgets.QLabel(self.Engineering)
        self.label_10.setGeometry(QtCore.QRect(410, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.WidgetManager.addWidget(self.Engineering)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.WidgetManager.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newGame_Button.setText(_translate("MainWindow", "New Game"))
        self.loadGame_Button.setText(_translate("MainWindow", "Load Game"))
        self.options_Button.setText(_translate("MainWindow", "Options"))
        self.galacticArmy_Button.setText(_translate("MainWindow", "Galactic Army"))
        self.rebellion_Button.setText(_translate("MainWindow", "Rebellion"))
        self.label.setText(_translate("MainWindow", "Pick your side"))
        self.Faction_Label.setText(_translate("MainWindow", "Galactic Army_Test"))
        self.groupBox.setTitle(_translate("MainWindow", "Controls:"))
        self.economy_Button.setText(_translate("MainWindow", "Economy"))
        self.research_Button.setText(_translate("MainWindow", "Research"))
        self.engineering_Button.setText(_translate("MainWindow", "Engineering"))
        self.endTurn_Button.setText(_translate("MainWindow", "End Turn"))
        self.army_Button.setText(_translate("MainWindow", "Army"))
        self.label_3.setText(_translate("MainWindow", "Rhen Var"))
        self.label_4.setText(_translate("MainWindow", "Kamino"))
        self.label_5.setText(_translate("MainWindow", "Mygeeto"))
        self.label_6.setText(_translate("MainWindow", "Geonosis"))
        self.label_7.setText(_translate("MainWindow", "Mustafar"))
        self.Credits_label.setText(_translate("MainWindow", "Credits:"))
        self.rhenVarFaction_Label.setText(_translate("MainWindow", "Galactic Army"))
        self.kaminoFaction_Label.setText(_translate("MainWindow", "Galactic Army"))
        self.mygeetoFaction_Label.setText(_translate("MainWindow", "Neutral"))
        self.mustafarFactio_Label.setText(_translate("MainWindow", "Rebellion"))
        self.geonosisFaction_Label.setText(_translate("MainWindow", "Rebellion"))
        self.creditCount_Label.setText(_translate("MainWindow", "600"))
        self.planetSelected_Label.setText(_translate("MainWindow", "Planet Selected:"))
        self.fromPlanet_Label.setText(_translate("MainWindow", "Kamino"))
        self.toPlanet_Label.setText(_translate("MainWindow", "Mygeeto"))
        self.Label_18.setText(_translate("MainWindow", "Total Troops:"))
        self.Label_17.setText(_translate("MainWindow", "Total Troops:"))
        self.fromFaction_Label.setText(_translate("MainWindow", "Galactic Army"))
        self.toFaction_Label.setText(_translate("MainWindow", "Neutral"))
        self.fromTo_Send.setText(_translate("MainWindow", "Send"))
        self.fromTo_Cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_19.setText(_translate("MainWindow", "------>"))
        self.label_20.setText(_translate("MainWindow", "Number of troops to travel"))
        self.movementStatus_Label.setText(_translate("MainWindow", "Occupy"))
        self.label_38.setText(_translate("MainWindow", "Total Fleet:"))
        self.label_40.setText(_translate("MainWindow", "Total Fleet:"))
        self.fromTroops_Label.setText(_translate("MainWindow", "100"))
        self.toTroops_Label.setText(_translate("MainWindow", "40"))
        self.armyCalculate_Button.setText(_translate("MainWindow", "Calculate"))
        self.label_28.setText(_translate("MainWindow", "Army"))
        self.armyCost_Label.setText(_translate("MainWindow", "Cost: "))
        self.armyUpkeep_Label.setText(_translate("MainWindow", "Upkeep: "))
        self.armyCredits_Label.setText(_translate("MainWindow", "Credits:"))
        self.armyCancel_Button.setText(_translate("MainWindow", "Cancel"))
        self.armyOrder_Button.setText(_translate("MainWindow", "Order"))
        self.label_26.setText(_translate("MainWindow", "Economy"))
        self.economyCreditsTurn_Label.setText(_translate("MainWindow", "100"))
        self.label_22.setText(_translate("MainWindow", "Credits:"))
        self.label_27.setText(_translate("MainWindow", "Overview"))
        self.economyCredits_Label.setText(_translate("MainWindow", "600"))
        self.label_23.setText(_translate("MainWindow", "Credits/Turn:"))
        self.economyBonds_Label.setText(_translate("MainWindow", "100"))
        self.label_34.setText(_translate("MainWindow", "Taxes:"))
        self.label_35.setText(_translate("MainWindow", "Breakdown"))
        self.economyTaxes_Label.setText(_translate("MainWindow", "600"))
        self.label_37.setText(_translate("MainWindow", "Bonds/Turn:"))
        self.label_39.setText(_translate("MainWindow", "Income:"))
        self.economyIncome_Label.setText(_translate("MainWindow", "600"))
        self.label_41.setText(_translate("MainWindow", "Army Upkeep:"))
        self.economyUpkeep_Label.setText(_translate("MainWindow", "0"))
        self.label_45.setText(_translate("MainWindow", "Expenses"))
        self.economyCancel_Button.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Set Taxes"))
        self.economy9_Button.setText(_translate("MainWindow", "9"))
        self.economyE_Button.setText(_translate("MainWindow", "E"))
        self.economy1_Button.setText(_translate("MainWindow", "1"))
        self.economyC_Button.setText(_translate("MainWindow", "C"))
        self.economy3_Button.setText(_translate("MainWindow", "3"))
        self.economy6_Button.setText(_translate("MainWindow", "6"))
        self.economy8_Button.setText(_translate("MainWindow", "8"))
        self.economy7_Button.setText(_translate("MainWindow", "7"))
        self.economy4_Button.setText(_translate("MainWindow", "4"))
        self.economy0_Button.setText(_translate("MainWindow", "0"))
        self.economy5_Button.setText(_translate("MainWindow", "5"))
        self.economy2_Button.setText(_translate("MainWindow", "2"))
        self.pushButton_13.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Combat Tactics"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Equipment"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Leadership"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Economy"))
        self.label_9.setText(_translate("MainWindow", "Research"))
        self.label_10.setText(_translate("MainWindow", "Engineering"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
